### ISSUE TITLE
Version 1 vs version 2?

### ISSUE THREAD

**Issue by dmccallie** [DougAnderson444/svelte-zoom-action#1]
Hello.

This is a very nice project that I'd like to incorporate into a SvelteKit app that I am working on. It's my first Svelte application (and I'm new to web development in general) so I have some pretty  basic questions.

Most importantly, your code appears to support two versions - panzoom and pzoom. Can you clarify what's going on there? Which version would you recommend be used for a simple image pan/zoom component, as part of a blog-like application?

Second, how would I install your code? Since the code is free of lots of dependencies, would the easiest approach be to just add selected parts of your source code into my project?  In other words, no need for an "npm install" command?

And finally, what license is the code offered under?

Thanks!

**Comment by dmccallie** [comment]
FWIW, after experimenting more, I was able to get the `pzoom` code below to work more or less as I needed.

I installed with ` npm install @douganderson444/panzoom-node`   and then cribbed some demo code from 
 `src/routes/index.svelte`

One question - I need to force the zoom scale to stop at 1.0, not going lower, so I hacked a call to:

> `zoomable.dispatchEvent(new CustomEvent('scaleTo', { detail: { scale: 1.0 } }))`

to send  the scale back to 1 whenever scale tried to go below 1.0  This works OK, but there is probably a better way to enforce a scrolling range?

And one more question - is there a way to stop panning when the scale is less than or equal to 1.0? In other words, when zoomed fully out to 1.0, I don't want panning to happen.


Thanks!

(see the corrected code in the comment below!)

**Comment by dmccallie** [comment]
Arrgh. Sloppy me, I pasted the wrong version of code. This is what's currently working, except for the ability to stop panning once the scale gets back to 1.0

Note that I had to use the "dispatch to home" event to stop scaling below 1.0  The other function creates an infinite loop.

```svelte
<script>
	import { pzoom } from '@douganderson444/panzoom-node'
	let zoomable, container;
	let handle;
	let scale = 1;
	let count = 10;
	let min = count;
	let values;

	$: if (scale) {
		values = [scale]; // match the directive scale level
	}
	$: if (zoomable?.style?.transform) console.log({ zoomable: zoomable.style.transform });
	
        function handleRangeChg(e) {
		zoomable.dispatchEvent(new CustomEvent('scaleTo', { detail: { scale: values[0] } }));
	}

	function goHome(e) {
		// dispatch custom event to zoomable element
		zoomable.dispatchEvent(new CustomEvent('home'));
	}

	const handleScaleChg = (e) => {
        scale = e.detail.scale;
        if (scale < 1.0) {
            //zoomable.dispatchEvent(new CustomEvent('scaleTo', { detail: { scale: 1.0 } }));
            zoomable.dispatchEvent(new CustomEvent('home'));
            }
	console.log('scale changed', scale);
	};
</script>

<div class="container" bind:this={container}>
	<div class="menu">
		<div>
			<button on:click={goHome}>Reset Zoom</button>
			<br />Zoom Level: {scale}
		</div>
	</div>
	<div
		class="zoomable flexbox"
		bind:this={zoomable}
		use:pzoom={{ panAnywhere: true }}
		on:scale={handleScaleChg}
	>
        <img src="https://photos.smugmug.com/ --- .jpg">

	</div>
</div>

<style>
	.container {
		border: 3px solid red;
		height: 400px;
		width: 600px;
		margin: 3em;
		/* overflow: hidden;  its set by the directive :) */
		/* touch-action: none;  its set by the directive :) */
		/* position: relative; its set by the directive :) */
	}
	.zoomable {
		border: 4px dashed blue;
		height: 50%;
		width: 50%;
		/* margin: 1em; */
		/* position: relative; its set by the directive :) */
	}
	.flexbox {
		display: flex;
		flex-wrap: nowrap;
		align-content: stretch;
		justify-content: space-evenly;
		align-items: stretch;
	}

	.menu {
		position: absolute;
		top: 10px;
		left: 10px;
		width: 400px;
		margin: 0.1em;
		padding: 2em;
		z-index: 10;
		background-color: rgba(133, 198, 255, 0.801);
	}
</style>

```

**Comment by DougAnderson444** [comment]
Hey there,

Great observations of various stages of my work in progress. At some point, I switched zoom models, but wanted to keep the old code, so I rename the second version to pzoom. 

I didn't get the zoom to home stuff working here yet, so the inifinite loop doesn't surprise me. Sorry about the mess...

Really what I should do is clean the whole repo up, but I haven't got to that yet. It sounds like you got the basics working, it'll just be some of the more advanced features that were a work-in-progress that will be buggy at the moment.

**Comment by dmccallie** [comment]
Thank you. I will keep an eye on your progress.

When and if you get around to more work, it would be nice to parameterize a minimum zoom level (like don’t go below 1.0) and to allow stopping of pan once zoom gets back to 1.0. Once I understand the inner code better, I’ll probably hack a few attempts….

**Comment by dmccallie** [comment]
Turns out that you did have a `min-scale` parameter that can be set as an attribute of the container. If you set that to 1.0, then there is no need to call the "scale to" custom event while zooming.

**Comment by DougAnderson444** [comment]
> This is a very nice project that I'd like to incorporate into a SvelteKit app that I am working on. It's my first Svelte application (and I'm new to web development in general) so I have some pretty basic questions.

Projects like these are a great way to dig into the Web API. I'll set aside some time to clean things up so it's more clear, hopefully you get something out of it in the meantime!

**Comment by DougAnderson444** [comment]
I cleaned up the example a bit, removed old code, hopefully the code is a bit more clear now. 

Pan/Zoom by Handle also now works!

**Comment by dmccallie** [comment]
Thanks!

I took a quick peek at the code and it is more clear, or perhaps I am slowly figuring out how it works :) I'll do some testing later on.

One thing to look at though - I ran into trouble using the min-scale attribute to set a clip of the scale to 1.0 (I don't want the user to zoom smaller than the container.)

Your code in `PinchZoom.tz` currently checks for scale < min-scale, and just leaves scale at the current value if the new scale is less than min-scale. 

```ts
	private _updateTransform(scale: number, x: number, y: number, allowChangeEvent: boolean) {
		// Avoid scaling to zero
		if (scale < this.minScale) return;

```
For me this creates a problem that due to scroll wheel granularity, you can get close to min-scale, but often not all the way to the actual min scale.  For example, scale ends up at 1.1 instead of 1.0

So I wonder if that code should clamp the scale to the minScale value instead of just refusing to go below minScale?  Something like this:

```ts
	private _updateTransform(scale: number, x: number, y: number, allowChangeEvent: boolean) {
		// Avoid scaling to zero -- and clamp to min-scale if try to go below
		if (scale < this.minScale) {
                      scale = this.minScale
                      return;
                }
```

Of course, I may be misunderstanding what's going on here....

**Comment by DougAnderson444** [comment]
Yep, good eyes. I fixed that just now. 

This code originally came from custom components (web components) so you can also just set the HTML element attr to `<div min-scale=1>` to get the desired effect
